# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ba7dcf2965ee80bf7b3c584327c06eb5f89264a25e7bafe2bc284c7e72a38874935e139934388c2ec9897e008bbbbda0b3870a11391a66bc4ba177052d79cff

test:
  secret_key_base: 89597c4036e4b1453a13bf04d9e09e5d4b768a162c538f03f0ea6626cee7c7a61c29a1e8084d4bed16a42144e31e8c6a4f2e9202c3960d1d2a309e6df3a75c26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
